-- 019: 국가 값을 ISO 3166-1 alpha-2 코드로 통일
--
-- 지금까지 국가를 **표시명 그대로** 저장했다. 그런데 표시명의 출처가 두 개였다:
--   users.region / programs.host_country  ← world_countries.dart (한글, '아르헨티나')
--   registrations.country                 ← ubf_chapters.json    (영문, 'ARGENTINA')
--
-- 두 값은 같은 나라를 가리키면서도 문자열이 달라 절대 일치하지 않는다. 그래서
-- 아래 세 곳이 조용히 틀렸다 — 오류가 나지 않아 아무도 눈치채지 못했다:
--   · 봉사 신청의 'domestic' 자격 (service_signups.js)
--   · 준비 현황의 국내/해외 코호트 집계 (programs.js readiness)
--   · 개최국 참석자의 항공편 스텝 생략 (앱)
--
-- 이제 세 컬럼 모두 ISO 코드('AR')를 저장한다. 표시명은 앱이 코드에서 만들며
-- 사용자 언어와 무관하게 영어로 보여준다.
--
-- 안전장치: 매핑에 없는 값은 **건드리지 않고 그대로 둔다.** 지우거나 NULL 로
-- 만들면 어느 나라였는지 복구할 수 없다. 앱에도 같은 매핑이 있어
-- (WorldCountries.isoForLegacy) 남은 값을 화면에서 해석한다.
--
-- 매핑을 임시 테이블이 아니라 각 UPDATE 안에 인라인한 이유:
-- migrate.js 는 구문을 하나씩 따로 실행하고 각각이 커밋된다. 임시 테이블은
-- 그 사이에 사라져 다음 구문에서 보이지 않는다.
--
-- 주의: migrate.js 는 이력을 추적하지 않고 매 실행마다 전체를 재적용한다.
-- 아래 UPDATE 는 이미 ISO 인 값에 매칭되지 않으므로 재실행해도 안전하다.
-- (마지막 조건 `<> m.iso` 가 그 역할을 한다.)

UPDATE users u
   SET region = m.iso
  FROM (VALUES
      ('AFGHANISTAN', 'AF'),
      ('ALBANIA', 'AL'),
      ('ALGERIA', 'DZ'),
      ('ANDORRA', 'AD'),
      ('ANGOLA', 'AO'),
      ('ARGENTINA', 'AR'),
      ('ARMENIA', 'AM'),
      ('AUSTRALIA', 'AU'),
      ('AUSTRIA', 'AT'),
      ('AZERBAIJAN', 'AZ'),
      ('BAHAMAS', 'BS'),
      ('BAHRAIN', 'BH'),
      ('BANGLADESH', 'BD'),
      ('BARBADOS', 'BB'),
      ('BELARUS', 'BY'),
      ('BELGIUM', 'BE'),
      ('BELIZE', 'BZ'),
      ('BENIN', 'BJ'),
      ('BHUTAN', 'BT'),
      ('BOLIVIA', 'BO'),
      ('BOSNIA AND HERZEGOVINA', 'BA'),
      ('BOTSWANA', 'BW'),
      ('BRASIL', 'BR'),
      ('BRAZIL', 'BR'),
      ('BRUNEI', 'BN'),
      ('BULGARIA', 'BG'),
      ('BURKINA FASO', 'BF'),
      ('BURUNDI', 'BI'),
      ('CABO VERDE', 'CV'),
      ('CAMBODIA', 'KH'),
      ('CAMEROON', 'CM'),
      ('CAMEROUN', 'CM'),
      ('CANADA', 'CA'),
      ('CENTRAL AFRICAN REPUBLIC', 'CF'),
      ('CHAD', 'TD'),
      ('CHILE', 'CL'),
      ('CHINA', 'CN'),
      ('COLOMBIA', 'CO'),
      ('COSTA RICA', 'CR'),
      ('CROATIA', 'HR'),
      ('CUBA', 'CU'),
      ('CYPRUS', 'CY'),
      ('CZECH REPUBLIC', 'CZ'),
      ('CZECHIA', 'CZ'),
      ('CÔTE D''IVOIRE', 'CI'),
      ('DENMARK', 'DK'),
      ('DJIBOUTI', 'DJ'),
      ('DOMINICAN REPUBLIC', 'DO'),
      ('DR CONGO', 'CD'),
      ('ECUADOR', 'EC'),
      ('EGYPT', 'EG'),
      ('EL SALVADOR', 'SV'),
      ('EQUATORIAL GUINEA', 'GQ'),
      ('ERITREA', 'ER'),
      ('ESTONIA', 'EE'),
      ('ESWATINI', 'SZ'),
      ('ETHIOPIA', 'ET'),
      ('FIJI', 'FJ'),
      ('FINLAND', 'FI'),
      ('FRANCE', 'FR'),
      ('GABON', 'GA'),
      ('GAMBIA', 'GM'),
      ('GEORGIA', 'GE'),
      ('GERMANY', 'DE'),
      ('GHANA', 'GH'),
      ('GREECE', 'GR'),
      ('GUATEMALA', 'GT'),
      ('GUINEA', 'GN'),
      ('GUINEA-BISSAU', 'GW'),
      ('GUYANA', 'GY'),
      ('HAITI', 'HT'),
      ('HONDURAS', 'HN'),
      ('HONG KONG', 'HK'),
      ('HUNGARY', 'HU'),
      ('ICELAND', 'IS'),
      ('INDIA', 'IN'),
      ('INDONESIA', 'ID'),
      ('IRAN', 'IR'),
      ('IRAQ', 'IQ'),
      ('IRELAND', 'IE'),
      ('ISRAEL', 'IL'),
      ('ITALY', 'IT'),
      ('JAMAICA', 'JM'),
      ('JAPAN', 'JP'),
      ('JORDAN', 'JO'),
      ('KAZAKHSTAN', 'KZ'),
      ('KENYA', 'KE'),
      ('KIRIBATI', 'KI'),
      ('KOREA', 'KR'),
      ('KOSOVO', 'XK'),
      ('KUWAIT', 'KW'),
      ('KYRGYZSTAN', 'KG'),
      ('LAOS', 'LA'),
      ('LATVIA', 'LV'),
      ('LEBANON', 'LB'),
      ('LESOTHO', 'LS'),
      ('LIBERIA', 'LR'),
      ('LIBYA', 'LY'),
      ('LIECHTENSTEIN', 'LI'),
      ('LITHUANIA', 'LT'),
      ('LUXEMBOURG', 'LU'),
      ('MACAU', 'MO'),
      ('MADAGASCAR', 'MG'),
      ('MALAWI', 'MW'),
      ('MALAYSIA', 'MY'),
      ('MALDIVES', 'MV'),
      ('MALI', 'ML'),
      ('MALTA', 'MT'),
      ('MARSHALL ISLANDS', 'MH'),
      ('MAURITIUS', 'MU'),
      ('MEXICO', 'MX'),
      ('MICRONESIA', 'FM'),
      ('MOLDOVA', 'MD'),
      ('MONACO', 'MC'),
      ('MONGOLIA', 'MN'),
      ('MONTENEGRO', 'ME'),
      ('MOROCCO', 'MA'),
      ('MOZAMBIQUE', 'MZ'),
      ('MYANMAR', 'MM'),
      ('NAMIBIA', 'NA'),
      ('NAURU', 'NR'),
      ('NEPAL', 'NP'),
      ('NETHERLANDS', 'NL'),
      ('NEW ZEALAND', 'NZ'),
      ('NICARAGUA', 'NI'),
      ('NIGER', 'NE'),
      ('NIGERIA', 'NG'),
      ('NORTH KOREA', 'KP'),
      ('NORTH MACEDONIA', 'MK'),
      ('NORWAY', 'NO'),
      ('OMAN', 'OM'),
      ('PAKISTAN', 'PK'),
      ('PALAU', 'PW'),
      ('PALESTINE', 'PS'),
      ('PANAMA', 'PA'),
      ('PAPUA NEW GUINEA', 'PG'),
      ('PARAGUAY', 'PY'),
      ('PERU', 'PE'),
      ('PHILIPPINES', 'PH'),
      ('POLAND', 'PL'),
      ('PORTUGAL', 'PT'),
      ('QATAR', 'QA'),
      ('REPUBLIC OF THE CONGO', 'CG'),
      ('ROMANIA', 'RO'),
      ('RUSSIA', 'RU'),
      ('RWANDA', 'RW'),
      ('SAMOA', 'WS'),
      ('SAN MARINO', 'SM'),
      ('SAUDI ARABIA', 'SA'),
      ('SENEGAL', 'SN'),
      ('SERBIA', 'RS'),
      ('SEYCHELLES', 'SC'),
      ('SIERRA LEONE', 'SL'),
      ('SINGAPORE', 'SG'),
      ('SLOVAKIA', 'SK'),
      ('SLOVENIA', 'SI'),
      ('SOLOMON ISLANDS', 'SB'),
      ('SOMALIA', 'SO'),
      ('SOUTH AFRICA', 'ZA'),
      ('SOUTH KOREA', 'KR'),
      ('SOUTH SUDAN', 'SS'),
      ('SPAIN', 'ES'),
      ('SRI LANKA', 'LK'),
      ('SRI-LANKA', 'LK'),
      ('SUDAN', 'SD'),
      ('SURINAME', 'SR'),
      ('SWEDEN', 'SE'),
      ('SWITZERLAND', 'CH'),
      ('SYRIA', 'SY'),
      ('SÃO TOMÉ AND PRÍNCIPE', 'ST'),
      ('TAIWAN', 'TW'),
      ('TAJIKISTAN', 'TJ'),
      ('TANZANIA', 'TZ'),
      ('THAILAND', 'TH'),
      ('TIMOR-LESTE', 'TL'),
      ('TOGO', 'TG'),
      ('TONGA', 'TO'),
      ('TRINIDAD AND TOBAGO', 'TT'),
      ('TUNISIA', 'TN'),
      ('TURKEY', 'TR'),
      ('TURKMENISTAN', 'TM'),
      ('TUVALU', 'TV'),
      ('TÜRKIYE', 'TR'),
      ('U. S. A.', 'US'),
      ('UGANDA', 'UG'),
      ('UKRAINE', 'UA'),
      ('UNITED ARAB EMIRATES', 'AE'),
      ('UNITED KINGDOM', 'GB'),
      ('UNITED STATES', 'US'),
      ('URUGUAY', 'UY'),
      ('UZBEKISTAN', 'UZ'),
      ('VANUATU', 'VU'),
      ('VATICAN CITY', 'VA'),
      ('VENEZUELA', 'VE'),
      ('VIETNAM', 'VN'),
      ('YEMEN', 'YE'),
      ('ZAMBIA', 'ZM'),
      ('ZIMBABWE', 'ZW'),
      ('가나', 'GH'),
      ('가봉', 'GA'),
      ('가이아나', 'GY'),
      ('감비아', 'GM'),
      ('과테말라', 'GT'),
      ('그리스', 'GR'),
      ('기니', 'GN'),
      ('기니비사우', 'GW'),
      ('나미비아', 'NA'),
      ('나우루', 'NR'),
      ('나이지리아', 'NG'),
      ('남수단', 'SS'),
      ('남아프리카공화국', 'ZA'),
      ('네덜란드', 'NL'),
      ('네팔', 'NP'),
      ('노르웨이', 'NO'),
      ('뉴질랜드', 'NZ'),
      ('니제르', 'NE'),
      ('니카라과', 'NI'),
      ('대만', 'TW'),
      ('대한민국', 'KR'),
      ('덴마크', 'DK'),
      ('도미니카공화국', 'DO'),
      ('독일', 'DE'),
      ('동티모르', 'TL'),
      ('라오스', 'LA'),
      ('라이베리아', 'LR'),
      ('라트비아', 'LV'),
      ('러시아', 'RU'),
      ('레바논', 'LB'),
      ('레소토', 'LS'),
      ('루마니아', 'RO'),
      ('룩셈부르크', 'LU'),
      ('르완다', 'RW'),
      ('리비아', 'LY'),
      ('리투아니아', 'LT'),
      ('리히텐슈타인', 'LI'),
      ('마다가스카르', 'MG'),
      ('마셜제도', 'MH'),
      ('마카오', 'MO'),
      ('말라위', 'MW'),
      ('말레이시아', 'MY'),
      ('말리', 'ML'),
      ('멕시코', 'MX'),
      ('모나코', 'MC'),
      ('모로코', 'MA'),
      ('모리셔스', 'MU'),
      ('모잠비크', 'MZ'),
      ('몬테네그로', 'ME'),
      ('몰도바', 'MD'),
      ('몰디브', 'MV'),
      ('몰타', 'MT'),
      ('몽골', 'MN'),
      ('미국', 'US'),
      ('미얀마', 'MM'),
      ('미크로네시아', 'FM'),
      ('바누아투', 'VU'),
      ('바레인', 'BH'),
      ('바베이도스', 'BB'),
      ('바티칸', 'VA'),
      ('바하마', 'BS'),
      ('방글라데시', 'BD'),
      ('베냉', 'BJ'),
      ('베네수엘라', 'VE'),
      ('베트남', 'VN'),
      ('벨기에', 'BE'),
      ('벨라루스', 'BY'),
      ('벨리즈', 'BZ'),
      ('보스니아헤르체고비나', 'BA'),
      ('보츠와나', 'BW'),
      ('볼리비아', 'BO'),
      ('부룬디', 'BI'),
      ('부르키나파소', 'BF'),
      ('부탄', 'BT'),
      ('북마케도니아', 'MK'),
      ('북한', 'KP'),
      ('불가리아', 'BG'),
      ('브라질', 'BR'),
      ('브루나이', 'BN'),
      ('사모아', 'WS'),
      ('사우디아라비아', 'SA'),
      ('산마리노', 'SM'),
      ('상투메프린시페', 'ST'),
      ('세네갈', 'SN'),
      ('세르비아', 'RS'),
      ('세이셸', 'SC'),
      ('소말리아', 'SO'),
      ('솔로몬제도', 'SB'),
      ('수단', 'SD'),
      ('수리남', 'SR'),
      ('스리랑카', 'LK'),
      ('스웨덴', 'SE'),
      ('스위스', 'CH'),
      ('스페인', 'ES'),
      ('슬로바키아', 'SK'),
      ('슬로베니아', 'SI'),
      ('시리아', 'SY'),
      ('시에라리온', 'SL'),
      ('싱가포르', 'SG'),
      ('아랍에미리트', 'AE'),
      ('아르메니아', 'AM'),
      ('아르헨티나', 'AR'),
      ('아이슬란드', 'IS'),
      ('아이티', 'HT'),
      ('아일랜드', 'IE'),
      ('아제르바이잔', 'AZ'),
      ('아프가니스탄', 'AF'),
      ('안도라', 'AD'),
      ('알바니아', 'AL'),
      ('알제리', 'DZ'),
      ('앙골라', 'AO'),
      ('에리트레아', 'ER'),
      ('에스와티니', 'SZ'),
      ('에스토니아', 'EE'),
      ('에콰도르', 'EC'),
      ('에티오피아', 'ET'),
      ('엘살바도르', 'SV'),
      ('영국', 'GB'),
      ('예멘', 'YE'),
      ('오만', 'OM'),
      ('오스트리아', 'AT'),
      ('온두라스', 'HN'),
      ('요르단', 'JO'),
      ('우간다', 'UG'),
      ('우루과이', 'UY'),
      ('우즈베키스탄', 'UZ'),
      ('우크라이나', 'UA'),
      ('이라크', 'IQ'),
      ('이란', 'IR'),
      ('이스라엘', 'IL'),
      ('이집트', 'EG'),
      ('이탈리아', 'IT'),
      ('인도', 'IN'),
      ('인도네시아', 'ID'),
      ('일본', 'JP'),
      ('자메이카', 'JM'),
      ('잠비아', 'ZM'),
      ('적도기니', 'GQ'),
      ('조지아', 'GE'),
      ('중국', 'CN'),
      ('중앙아프리카공화국', 'CF'),
      ('지부티', 'DJ'),
      ('짐바브웨', 'ZW'),
      ('차드', 'TD'),
      ('체코', 'CZ'),
      ('칠레', 'CL'),
      ('카메룬', 'CM'),
      ('카보베르데', 'CV'),
      ('카자흐스탄', 'KZ'),
      ('카타르', 'QA'),
      ('캄보디아', 'KH'),
      ('캐나다', 'CA'),
      ('케냐', 'KE'),
      ('코소보', 'XK'),
      ('코스타리카', 'CR'),
      ('코트디부아르', 'CI'),
      ('콜롬비아', 'CO'),
      ('콩고공화국', 'CG'),
      ('콩고민주공화국', 'CD'),
      ('쿠바', 'CU'),
      ('쿠웨이트', 'KW'),
      ('크로아티아', 'HR'),
      ('키르기스스탄', 'KG'),
      ('키리바시', 'KI'),
      ('키프로스', 'CY'),
      ('타지키스탄', 'TJ'),
      ('탄자니아', 'TZ'),
      ('태국', 'TH'),
      ('터키', 'TR'),
      ('토고', 'TG'),
      ('통가', 'TO'),
      ('투르크메니스탄', 'TM'),
      ('투발루', 'TV'),
      ('튀니지', 'TN'),
      ('트리니다드토바고', 'TT'),
      ('파나마', 'PA'),
      ('파라과이', 'PY'),
      ('파키스탄', 'PK'),
      ('파푸아뉴기니', 'PG'),
      ('팔라우', 'PW'),
      ('팔레스타인', 'PS'),
      ('페루', 'PE'),
      ('포르투갈', 'PT'),
      ('폴란드', 'PL'),
      ('프랑스', 'FR'),
      ('피지', 'FJ'),
      ('핀란드', 'FI'),
      ('필리핀', 'PH'),
      ('헝가리', 'HU'),
      ('호주', 'AU'),
      ('홍콩', 'HK')
  ) AS m(legacy, iso)
 WHERE u.region IS NOT NULL
   AND upper(trim(u.region)) = upper(m.legacy)
   AND u.region <> m.iso;

UPDATE programs p
   SET host_country = m.iso
  FROM (VALUES
      ('AFGHANISTAN', 'AF'),
      ('ALBANIA', 'AL'),
      ('ALGERIA', 'DZ'),
      ('ANDORRA', 'AD'),
      ('ANGOLA', 'AO'),
      ('ARGENTINA', 'AR'),
      ('ARMENIA', 'AM'),
      ('AUSTRALIA', 'AU'),
      ('AUSTRIA', 'AT'),
      ('AZERBAIJAN', 'AZ'),
      ('BAHAMAS', 'BS'),
      ('BAHRAIN', 'BH'),
      ('BANGLADESH', 'BD'),
      ('BARBADOS', 'BB'),
      ('BELARUS', 'BY'),
      ('BELGIUM', 'BE'),
      ('BELIZE', 'BZ'),
      ('BENIN', 'BJ'),
      ('BHUTAN', 'BT'),
      ('BOLIVIA', 'BO'),
      ('BOSNIA AND HERZEGOVINA', 'BA'),
      ('BOTSWANA', 'BW'),
      ('BRASIL', 'BR'),
      ('BRAZIL', 'BR'),
      ('BRUNEI', 'BN'),
      ('BULGARIA', 'BG'),
      ('BURKINA FASO', 'BF'),
      ('BURUNDI', 'BI'),
      ('CABO VERDE', 'CV'),
      ('CAMBODIA', 'KH'),
      ('CAMEROON', 'CM'),
      ('CAMEROUN', 'CM'),
      ('CANADA', 'CA'),
      ('CENTRAL AFRICAN REPUBLIC', 'CF'),
      ('CHAD', 'TD'),
      ('CHILE', 'CL'),
      ('CHINA', 'CN'),
      ('COLOMBIA', 'CO'),
      ('COSTA RICA', 'CR'),
      ('CROATIA', 'HR'),
      ('CUBA', 'CU'),
      ('CYPRUS', 'CY'),
      ('CZECH REPUBLIC', 'CZ'),
      ('CZECHIA', 'CZ'),
      ('CÔTE D''IVOIRE', 'CI'),
      ('DENMARK', 'DK'),
      ('DJIBOUTI', 'DJ'),
      ('DOMINICAN REPUBLIC', 'DO'),
      ('DR CONGO', 'CD'),
      ('ECUADOR', 'EC'),
      ('EGYPT', 'EG'),
      ('EL SALVADOR', 'SV'),
      ('EQUATORIAL GUINEA', 'GQ'),
      ('ERITREA', 'ER'),
      ('ESTONIA', 'EE'),
      ('ESWATINI', 'SZ'),
      ('ETHIOPIA', 'ET'),
      ('FIJI', 'FJ'),
      ('FINLAND', 'FI'),
      ('FRANCE', 'FR'),
      ('GABON', 'GA'),
      ('GAMBIA', 'GM'),
      ('GEORGIA', 'GE'),
      ('GERMANY', 'DE'),
      ('GHANA', 'GH'),
      ('GREECE', 'GR'),
      ('GUATEMALA', 'GT'),
      ('GUINEA', 'GN'),
      ('GUINEA-BISSAU', 'GW'),
      ('GUYANA', 'GY'),
      ('HAITI', 'HT'),
      ('HONDURAS', 'HN'),
      ('HONG KONG', 'HK'),
      ('HUNGARY', 'HU'),
      ('ICELAND', 'IS'),
      ('INDIA', 'IN'),
      ('INDONESIA', 'ID'),
      ('IRAN', 'IR'),
      ('IRAQ', 'IQ'),
      ('IRELAND', 'IE'),
      ('ISRAEL', 'IL'),
      ('ITALY', 'IT'),
      ('JAMAICA', 'JM'),
      ('JAPAN', 'JP'),
      ('JORDAN', 'JO'),
      ('KAZAKHSTAN', 'KZ'),
      ('KENYA', 'KE'),
      ('KIRIBATI', 'KI'),
      ('KOREA', 'KR'),
      ('KOSOVO', 'XK'),
      ('KUWAIT', 'KW'),
      ('KYRGYZSTAN', 'KG'),
      ('LAOS', 'LA'),
      ('LATVIA', 'LV'),
      ('LEBANON', 'LB'),
      ('LESOTHO', 'LS'),
      ('LIBERIA', 'LR'),
      ('LIBYA', 'LY'),
      ('LIECHTENSTEIN', 'LI'),
      ('LITHUANIA', 'LT'),
      ('LUXEMBOURG', 'LU'),
      ('MACAU', 'MO'),
      ('MADAGASCAR', 'MG'),
      ('MALAWI', 'MW'),
      ('MALAYSIA', 'MY'),
      ('MALDIVES', 'MV'),
      ('MALI', 'ML'),
      ('MALTA', 'MT'),
      ('MARSHALL ISLANDS', 'MH'),
      ('MAURITIUS', 'MU'),
      ('MEXICO', 'MX'),
      ('MICRONESIA', 'FM'),
      ('MOLDOVA', 'MD'),
      ('MONACO', 'MC'),
      ('MONGOLIA', 'MN'),
      ('MONTENEGRO', 'ME'),
      ('MOROCCO', 'MA'),
      ('MOZAMBIQUE', 'MZ'),
      ('MYANMAR', 'MM'),
      ('NAMIBIA', 'NA'),
      ('NAURU', 'NR'),
      ('NEPAL', 'NP'),
      ('NETHERLANDS', 'NL'),
      ('NEW ZEALAND', 'NZ'),
      ('NICARAGUA', 'NI'),
      ('NIGER', 'NE'),
      ('NIGERIA', 'NG'),
      ('NORTH KOREA', 'KP'),
      ('NORTH MACEDONIA', 'MK'),
      ('NORWAY', 'NO'),
      ('OMAN', 'OM'),
      ('PAKISTAN', 'PK'),
      ('PALAU', 'PW'),
      ('PALESTINE', 'PS'),
      ('PANAMA', 'PA'),
      ('PAPUA NEW GUINEA', 'PG'),
      ('PARAGUAY', 'PY'),
      ('PERU', 'PE'),
      ('PHILIPPINES', 'PH'),
      ('POLAND', 'PL'),
      ('PORTUGAL', 'PT'),
      ('QATAR', 'QA'),
      ('REPUBLIC OF THE CONGO', 'CG'),
      ('ROMANIA', 'RO'),
      ('RUSSIA', 'RU'),
      ('RWANDA', 'RW'),
      ('SAMOA', 'WS'),
      ('SAN MARINO', 'SM'),
      ('SAUDI ARABIA', 'SA'),
      ('SENEGAL', 'SN'),
      ('SERBIA', 'RS'),
      ('SEYCHELLES', 'SC'),
      ('SIERRA LEONE', 'SL'),
      ('SINGAPORE', 'SG'),
      ('SLOVAKIA', 'SK'),
      ('SLOVENIA', 'SI'),
      ('SOLOMON ISLANDS', 'SB'),
      ('SOMALIA', 'SO'),
      ('SOUTH AFRICA', 'ZA'),
      ('SOUTH KOREA', 'KR'),
      ('SOUTH SUDAN', 'SS'),
      ('SPAIN', 'ES'),
      ('SRI LANKA', 'LK'),
      ('SRI-LANKA', 'LK'),
      ('SUDAN', 'SD'),
      ('SURINAME', 'SR'),
      ('SWEDEN', 'SE'),
      ('SWITZERLAND', 'CH'),
      ('SYRIA', 'SY'),
      ('SÃO TOMÉ AND PRÍNCIPE', 'ST'),
      ('TAIWAN', 'TW'),
      ('TAJIKISTAN', 'TJ'),
      ('TANZANIA', 'TZ'),
      ('THAILAND', 'TH'),
      ('TIMOR-LESTE', 'TL'),
      ('TOGO', 'TG'),
      ('TONGA', 'TO'),
      ('TRINIDAD AND TOBAGO', 'TT'),
      ('TUNISIA', 'TN'),
      ('TURKEY', 'TR'),
      ('TURKMENISTAN', 'TM'),
      ('TUVALU', 'TV'),
      ('TÜRKIYE', 'TR'),
      ('U. S. A.', 'US'),
      ('UGANDA', 'UG'),
      ('UKRAINE', 'UA'),
      ('UNITED ARAB EMIRATES', 'AE'),
      ('UNITED KINGDOM', 'GB'),
      ('UNITED STATES', 'US'),
      ('URUGUAY', 'UY'),
      ('UZBEKISTAN', 'UZ'),
      ('VANUATU', 'VU'),
      ('VATICAN CITY', 'VA'),
      ('VENEZUELA', 'VE'),
      ('VIETNAM', 'VN'),
      ('YEMEN', 'YE'),
      ('ZAMBIA', 'ZM'),
      ('ZIMBABWE', 'ZW'),
      ('가나', 'GH'),
      ('가봉', 'GA'),
      ('가이아나', 'GY'),
      ('감비아', 'GM'),
      ('과테말라', 'GT'),
      ('그리스', 'GR'),
      ('기니', 'GN'),
      ('기니비사우', 'GW'),
      ('나미비아', 'NA'),
      ('나우루', 'NR'),
      ('나이지리아', 'NG'),
      ('남수단', 'SS'),
      ('남아프리카공화국', 'ZA'),
      ('네덜란드', 'NL'),
      ('네팔', 'NP'),
      ('노르웨이', 'NO'),
      ('뉴질랜드', 'NZ'),
      ('니제르', 'NE'),
      ('니카라과', 'NI'),
      ('대만', 'TW'),
      ('대한민국', 'KR'),
      ('덴마크', 'DK'),
      ('도미니카공화국', 'DO'),
      ('독일', 'DE'),
      ('동티모르', 'TL'),
      ('라오스', 'LA'),
      ('라이베리아', 'LR'),
      ('라트비아', 'LV'),
      ('러시아', 'RU'),
      ('레바논', 'LB'),
      ('레소토', 'LS'),
      ('루마니아', 'RO'),
      ('룩셈부르크', 'LU'),
      ('르완다', 'RW'),
      ('리비아', 'LY'),
      ('리투아니아', 'LT'),
      ('리히텐슈타인', 'LI'),
      ('마다가스카르', 'MG'),
      ('마셜제도', 'MH'),
      ('마카오', 'MO'),
      ('말라위', 'MW'),
      ('말레이시아', 'MY'),
      ('말리', 'ML'),
      ('멕시코', 'MX'),
      ('모나코', 'MC'),
      ('모로코', 'MA'),
      ('모리셔스', 'MU'),
      ('모잠비크', 'MZ'),
      ('몬테네그로', 'ME'),
      ('몰도바', 'MD'),
      ('몰디브', 'MV'),
      ('몰타', 'MT'),
      ('몽골', 'MN'),
      ('미국', 'US'),
      ('미얀마', 'MM'),
      ('미크로네시아', 'FM'),
      ('바누아투', 'VU'),
      ('바레인', 'BH'),
      ('바베이도스', 'BB'),
      ('바티칸', 'VA'),
      ('바하마', 'BS'),
      ('방글라데시', 'BD'),
      ('베냉', 'BJ'),
      ('베네수엘라', 'VE'),
      ('베트남', 'VN'),
      ('벨기에', 'BE'),
      ('벨라루스', 'BY'),
      ('벨리즈', 'BZ'),
      ('보스니아헤르체고비나', 'BA'),
      ('보츠와나', 'BW'),
      ('볼리비아', 'BO'),
      ('부룬디', 'BI'),
      ('부르키나파소', 'BF'),
      ('부탄', 'BT'),
      ('북마케도니아', 'MK'),
      ('북한', 'KP'),
      ('불가리아', 'BG'),
      ('브라질', 'BR'),
      ('브루나이', 'BN'),
      ('사모아', 'WS'),
      ('사우디아라비아', 'SA'),
      ('산마리노', 'SM'),
      ('상투메프린시페', 'ST'),
      ('세네갈', 'SN'),
      ('세르비아', 'RS'),
      ('세이셸', 'SC'),
      ('소말리아', 'SO'),
      ('솔로몬제도', 'SB'),
      ('수단', 'SD'),
      ('수리남', 'SR'),
      ('스리랑카', 'LK'),
      ('스웨덴', 'SE'),
      ('스위스', 'CH'),
      ('스페인', 'ES'),
      ('슬로바키아', 'SK'),
      ('슬로베니아', 'SI'),
      ('시리아', 'SY'),
      ('시에라리온', 'SL'),
      ('싱가포르', 'SG'),
      ('아랍에미리트', 'AE'),
      ('아르메니아', 'AM'),
      ('아르헨티나', 'AR'),
      ('아이슬란드', 'IS'),
      ('아이티', 'HT'),
      ('아일랜드', 'IE'),
      ('아제르바이잔', 'AZ'),
      ('아프가니스탄', 'AF'),
      ('안도라', 'AD'),
      ('알바니아', 'AL'),
      ('알제리', 'DZ'),
      ('앙골라', 'AO'),
      ('에리트레아', 'ER'),
      ('에스와티니', 'SZ'),
      ('에스토니아', 'EE'),
      ('에콰도르', 'EC'),
      ('에티오피아', 'ET'),
      ('엘살바도르', 'SV'),
      ('영국', 'GB'),
      ('예멘', 'YE'),
      ('오만', 'OM'),
      ('오스트리아', 'AT'),
      ('온두라스', 'HN'),
      ('요르단', 'JO'),
      ('우간다', 'UG'),
      ('우루과이', 'UY'),
      ('우즈베키스탄', 'UZ'),
      ('우크라이나', 'UA'),
      ('이라크', 'IQ'),
      ('이란', 'IR'),
      ('이스라엘', 'IL'),
      ('이집트', 'EG'),
      ('이탈리아', 'IT'),
      ('인도', 'IN'),
      ('인도네시아', 'ID'),
      ('일본', 'JP'),
      ('자메이카', 'JM'),
      ('잠비아', 'ZM'),
      ('적도기니', 'GQ'),
      ('조지아', 'GE'),
      ('중국', 'CN'),
      ('중앙아프리카공화국', 'CF'),
      ('지부티', 'DJ'),
      ('짐바브웨', 'ZW'),
      ('차드', 'TD'),
      ('체코', 'CZ'),
      ('칠레', 'CL'),
      ('카메룬', 'CM'),
      ('카보베르데', 'CV'),
      ('카자흐스탄', 'KZ'),
      ('카타르', 'QA'),
      ('캄보디아', 'KH'),
      ('캐나다', 'CA'),
      ('케냐', 'KE'),
      ('코소보', 'XK'),
      ('코스타리카', 'CR'),
      ('코트디부아르', 'CI'),
      ('콜롬비아', 'CO'),
      ('콩고공화국', 'CG'),
      ('콩고민주공화국', 'CD'),
      ('쿠바', 'CU'),
      ('쿠웨이트', 'KW'),
      ('크로아티아', 'HR'),
      ('키르기스스탄', 'KG'),
      ('키리바시', 'KI'),
      ('키프로스', 'CY'),
      ('타지키스탄', 'TJ'),
      ('탄자니아', 'TZ'),
      ('태국', 'TH'),
      ('터키', 'TR'),
      ('토고', 'TG'),
      ('통가', 'TO'),
      ('투르크메니스탄', 'TM'),
      ('투발루', 'TV'),
      ('튀니지', 'TN'),
      ('트리니다드토바고', 'TT'),
      ('파나마', 'PA'),
      ('파라과이', 'PY'),
      ('파키스탄', 'PK'),
      ('파푸아뉴기니', 'PG'),
      ('팔라우', 'PW'),
      ('팔레스타인', 'PS'),
      ('페루', 'PE'),
      ('포르투갈', 'PT'),
      ('폴란드', 'PL'),
      ('프랑스', 'FR'),
      ('피지', 'FJ'),
      ('핀란드', 'FI'),
      ('필리핀', 'PH'),
      ('헝가리', 'HU'),
      ('호주', 'AU'),
      ('홍콩', 'HK')
  ) AS m(legacy, iso)
 WHERE p.host_country IS NOT NULL
   AND upper(trim(p.host_country)) = upper(m.legacy)
   AND p.host_country <> m.iso;

UPDATE registrations r
   SET country = m.iso
  FROM (VALUES
      ('AFGHANISTAN', 'AF'),
      ('ALBANIA', 'AL'),
      ('ALGERIA', 'DZ'),
      ('ANDORRA', 'AD'),
      ('ANGOLA', 'AO'),
      ('ARGENTINA', 'AR'),
      ('ARMENIA', 'AM'),
      ('AUSTRALIA', 'AU'),
      ('AUSTRIA', 'AT'),
      ('AZERBAIJAN', 'AZ'),
      ('BAHAMAS', 'BS'),
      ('BAHRAIN', 'BH'),
      ('BANGLADESH', 'BD'),
      ('BARBADOS', 'BB'),
      ('BELARUS', 'BY'),
      ('BELGIUM', 'BE'),
      ('BELIZE', 'BZ'),
      ('BENIN', 'BJ'),
      ('BHUTAN', 'BT'),
      ('BOLIVIA', 'BO'),
      ('BOSNIA AND HERZEGOVINA', 'BA'),
      ('BOTSWANA', 'BW'),
      ('BRASIL', 'BR'),
      ('BRAZIL', 'BR'),
      ('BRUNEI', 'BN'),
      ('BULGARIA', 'BG'),
      ('BURKINA FASO', 'BF'),
      ('BURUNDI', 'BI'),
      ('CABO VERDE', 'CV'),
      ('CAMBODIA', 'KH'),
      ('CAMEROON', 'CM'),
      ('CAMEROUN', 'CM'),
      ('CANADA', 'CA'),
      ('CENTRAL AFRICAN REPUBLIC', 'CF'),
      ('CHAD', 'TD'),
      ('CHILE', 'CL'),
      ('CHINA', 'CN'),
      ('COLOMBIA', 'CO'),
      ('COSTA RICA', 'CR'),
      ('CROATIA', 'HR'),
      ('CUBA', 'CU'),
      ('CYPRUS', 'CY'),
      ('CZECH REPUBLIC', 'CZ'),
      ('CZECHIA', 'CZ'),
      ('CÔTE D''IVOIRE', 'CI'),
      ('DENMARK', 'DK'),
      ('DJIBOUTI', 'DJ'),
      ('DOMINICAN REPUBLIC', 'DO'),
      ('DR CONGO', 'CD'),
      ('ECUADOR', 'EC'),
      ('EGYPT', 'EG'),
      ('EL SALVADOR', 'SV'),
      ('EQUATORIAL GUINEA', 'GQ'),
      ('ERITREA', 'ER'),
      ('ESTONIA', 'EE'),
      ('ESWATINI', 'SZ'),
      ('ETHIOPIA', 'ET'),
      ('FIJI', 'FJ'),
      ('FINLAND', 'FI'),
      ('FRANCE', 'FR'),
      ('GABON', 'GA'),
      ('GAMBIA', 'GM'),
      ('GEORGIA', 'GE'),
      ('GERMANY', 'DE'),
      ('GHANA', 'GH'),
      ('GREECE', 'GR'),
      ('GUATEMALA', 'GT'),
      ('GUINEA', 'GN'),
      ('GUINEA-BISSAU', 'GW'),
      ('GUYANA', 'GY'),
      ('HAITI', 'HT'),
      ('HONDURAS', 'HN'),
      ('HONG KONG', 'HK'),
      ('HUNGARY', 'HU'),
      ('ICELAND', 'IS'),
      ('INDIA', 'IN'),
      ('INDONESIA', 'ID'),
      ('IRAN', 'IR'),
      ('IRAQ', 'IQ'),
      ('IRELAND', 'IE'),
      ('ISRAEL', 'IL'),
      ('ITALY', 'IT'),
      ('JAMAICA', 'JM'),
      ('JAPAN', 'JP'),
      ('JORDAN', 'JO'),
      ('KAZAKHSTAN', 'KZ'),
      ('KENYA', 'KE'),
      ('KIRIBATI', 'KI'),
      ('KOREA', 'KR'),
      ('KOSOVO', 'XK'),
      ('KUWAIT', 'KW'),
      ('KYRGYZSTAN', 'KG'),
      ('LAOS', 'LA'),
      ('LATVIA', 'LV'),
      ('LEBANON', 'LB'),
      ('LESOTHO', 'LS'),
      ('LIBERIA', 'LR'),
      ('LIBYA', 'LY'),
      ('LIECHTENSTEIN', 'LI'),
      ('LITHUANIA', 'LT'),
      ('LUXEMBOURG', 'LU'),
      ('MACAU', 'MO'),
      ('MADAGASCAR', 'MG'),
      ('MALAWI', 'MW'),
      ('MALAYSIA', 'MY'),
      ('MALDIVES', 'MV'),
      ('MALI', 'ML'),
      ('MALTA', 'MT'),
      ('MARSHALL ISLANDS', 'MH'),
      ('MAURITIUS', 'MU'),
      ('MEXICO', 'MX'),
      ('MICRONESIA', 'FM'),
      ('MOLDOVA', 'MD'),
      ('MONACO', 'MC'),
      ('MONGOLIA', 'MN'),
      ('MONTENEGRO', 'ME'),
      ('MOROCCO', 'MA'),
      ('MOZAMBIQUE', 'MZ'),
      ('MYANMAR', 'MM'),
      ('NAMIBIA', 'NA'),
      ('NAURU', 'NR'),
      ('NEPAL', 'NP'),
      ('NETHERLANDS', 'NL'),
      ('NEW ZEALAND', 'NZ'),
      ('NICARAGUA', 'NI'),
      ('NIGER', 'NE'),
      ('NIGERIA', 'NG'),
      ('NORTH KOREA', 'KP'),
      ('NORTH MACEDONIA', 'MK'),
      ('NORWAY', 'NO'),
      ('OMAN', 'OM'),
      ('PAKISTAN', 'PK'),
      ('PALAU', 'PW'),
      ('PALESTINE', 'PS'),
      ('PANAMA', 'PA'),
      ('PAPUA NEW GUINEA', 'PG'),
      ('PARAGUAY', 'PY'),
      ('PERU', 'PE'),
      ('PHILIPPINES', 'PH'),
      ('POLAND', 'PL'),
      ('PORTUGAL', 'PT'),
      ('QATAR', 'QA'),
      ('REPUBLIC OF THE CONGO', 'CG'),
      ('ROMANIA', 'RO'),
      ('RUSSIA', 'RU'),
      ('RWANDA', 'RW'),
      ('SAMOA', 'WS'),
      ('SAN MARINO', 'SM'),
      ('SAUDI ARABIA', 'SA'),
      ('SENEGAL', 'SN'),
      ('SERBIA', 'RS'),
      ('SEYCHELLES', 'SC'),
      ('SIERRA LEONE', 'SL'),
      ('SINGAPORE', 'SG'),
      ('SLOVAKIA', 'SK'),
      ('SLOVENIA', 'SI'),
      ('SOLOMON ISLANDS', 'SB'),
      ('SOMALIA', 'SO'),
      ('SOUTH AFRICA', 'ZA'),
      ('SOUTH KOREA', 'KR'),
      ('SOUTH SUDAN', 'SS'),
      ('SPAIN', 'ES'),
      ('SRI LANKA', 'LK'),
      ('SRI-LANKA', 'LK'),
      ('SUDAN', 'SD'),
      ('SURINAME', 'SR'),
      ('SWEDEN', 'SE'),
      ('SWITZERLAND', 'CH'),
      ('SYRIA', 'SY'),
      ('SÃO TOMÉ AND PRÍNCIPE', 'ST'),
      ('TAIWAN', 'TW'),
      ('TAJIKISTAN', 'TJ'),
      ('TANZANIA', 'TZ'),
      ('THAILAND', 'TH'),
      ('TIMOR-LESTE', 'TL'),
      ('TOGO', 'TG'),
      ('TONGA', 'TO'),
      ('TRINIDAD AND TOBAGO', 'TT'),
      ('TUNISIA', 'TN'),
      ('TURKEY', 'TR'),
      ('TURKMENISTAN', 'TM'),
      ('TUVALU', 'TV'),
      ('TÜRKIYE', 'TR'),
      ('U. S. A.', 'US'),
      ('UGANDA', 'UG'),
      ('UKRAINE', 'UA'),
      ('UNITED ARAB EMIRATES', 'AE'),
      ('UNITED KINGDOM', 'GB'),
      ('UNITED STATES', 'US'),
      ('URUGUAY', 'UY'),
      ('UZBEKISTAN', 'UZ'),
      ('VANUATU', 'VU'),
      ('VATICAN CITY', 'VA'),
      ('VENEZUELA', 'VE'),
      ('VIETNAM', 'VN'),
      ('YEMEN', 'YE'),
      ('ZAMBIA', 'ZM'),
      ('ZIMBABWE', 'ZW'),
      ('가나', 'GH'),
      ('가봉', 'GA'),
      ('가이아나', 'GY'),
      ('감비아', 'GM'),
      ('과테말라', 'GT'),
      ('그리스', 'GR'),
      ('기니', 'GN'),
      ('기니비사우', 'GW'),
      ('나미비아', 'NA'),
      ('나우루', 'NR'),
      ('나이지리아', 'NG'),
      ('남수단', 'SS'),
      ('남아프리카공화국', 'ZA'),
      ('네덜란드', 'NL'),
      ('네팔', 'NP'),
      ('노르웨이', 'NO'),
      ('뉴질랜드', 'NZ'),
      ('니제르', 'NE'),
      ('니카라과', 'NI'),
      ('대만', 'TW'),
      ('대한민국', 'KR'),
      ('덴마크', 'DK'),
      ('도미니카공화국', 'DO'),
      ('독일', 'DE'),
      ('동티모르', 'TL'),
      ('라오스', 'LA'),
      ('라이베리아', 'LR'),
      ('라트비아', 'LV'),
      ('러시아', 'RU'),
      ('레바논', 'LB'),
      ('레소토', 'LS'),
      ('루마니아', 'RO'),
      ('룩셈부르크', 'LU'),
      ('르완다', 'RW'),
      ('리비아', 'LY'),
      ('리투아니아', 'LT'),
      ('리히텐슈타인', 'LI'),
      ('마다가스카르', 'MG'),
      ('마셜제도', 'MH'),
      ('마카오', 'MO'),
      ('말라위', 'MW'),
      ('말레이시아', 'MY'),
      ('말리', 'ML'),
      ('멕시코', 'MX'),
      ('모나코', 'MC'),
      ('모로코', 'MA'),
      ('모리셔스', 'MU'),
      ('모잠비크', 'MZ'),
      ('몬테네그로', 'ME'),
      ('몰도바', 'MD'),
      ('몰디브', 'MV'),
      ('몰타', 'MT'),
      ('몽골', 'MN'),
      ('미국', 'US'),
      ('미얀마', 'MM'),
      ('미크로네시아', 'FM'),
      ('바누아투', 'VU'),
      ('바레인', 'BH'),
      ('바베이도스', 'BB'),
      ('바티칸', 'VA'),
      ('바하마', 'BS'),
      ('방글라데시', 'BD'),
      ('베냉', 'BJ'),
      ('베네수엘라', 'VE'),
      ('베트남', 'VN'),
      ('벨기에', 'BE'),
      ('벨라루스', 'BY'),
      ('벨리즈', 'BZ'),
      ('보스니아헤르체고비나', 'BA'),
      ('보츠와나', 'BW'),
      ('볼리비아', 'BO'),
      ('부룬디', 'BI'),
      ('부르키나파소', 'BF'),
      ('부탄', 'BT'),
      ('북마케도니아', 'MK'),
      ('북한', 'KP'),
      ('불가리아', 'BG'),
      ('브라질', 'BR'),
      ('브루나이', 'BN'),
      ('사모아', 'WS'),
      ('사우디아라비아', 'SA'),
      ('산마리노', 'SM'),
      ('상투메프린시페', 'ST'),
      ('세네갈', 'SN'),
      ('세르비아', 'RS'),
      ('세이셸', 'SC'),
      ('소말리아', 'SO'),
      ('솔로몬제도', 'SB'),
      ('수단', 'SD'),
      ('수리남', 'SR'),
      ('스리랑카', 'LK'),
      ('스웨덴', 'SE'),
      ('스위스', 'CH'),
      ('스페인', 'ES'),
      ('슬로바키아', 'SK'),
      ('슬로베니아', 'SI'),
      ('시리아', 'SY'),
      ('시에라리온', 'SL'),
      ('싱가포르', 'SG'),
      ('아랍에미리트', 'AE'),
      ('아르메니아', 'AM'),
      ('아르헨티나', 'AR'),
      ('아이슬란드', 'IS'),
      ('아이티', 'HT'),
      ('아일랜드', 'IE'),
      ('아제르바이잔', 'AZ'),
      ('아프가니스탄', 'AF'),
      ('안도라', 'AD'),
      ('알바니아', 'AL'),
      ('알제리', 'DZ'),
      ('앙골라', 'AO'),
      ('에리트레아', 'ER'),
      ('에스와티니', 'SZ'),
      ('에스토니아', 'EE'),
      ('에콰도르', 'EC'),
      ('에티오피아', 'ET'),
      ('엘살바도르', 'SV'),
      ('영국', 'GB'),
      ('예멘', 'YE'),
      ('오만', 'OM'),
      ('오스트리아', 'AT'),
      ('온두라스', 'HN'),
      ('요르단', 'JO'),
      ('우간다', 'UG'),
      ('우루과이', 'UY'),
      ('우즈베키스탄', 'UZ'),
      ('우크라이나', 'UA'),
      ('이라크', 'IQ'),
      ('이란', 'IR'),
      ('이스라엘', 'IL'),
      ('이집트', 'EG'),
      ('이탈리아', 'IT'),
      ('인도', 'IN'),
      ('인도네시아', 'ID'),
      ('일본', 'JP'),
      ('자메이카', 'JM'),
      ('잠비아', 'ZM'),
      ('적도기니', 'GQ'),
      ('조지아', 'GE'),
      ('중국', 'CN'),
      ('중앙아프리카공화국', 'CF'),
      ('지부티', 'DJ'),
      ('짐바브웨', 'ZW'),
      ('차드', 'TD'),
      ('체코', 'CZ'),
      ('칠레', 'CL'),
      ('카메룬', 'CM'),
      ('카보베르데', 'CV'),
      ('카자흐스탄', 'KZ'),
      ('카타르', 'QA'),
      ('캄보디아', 'KH'),
      ('캐나다', 'CA'),
      ('케냐', 'KE'),
      ('코소보', 'XK'),
      ('코스타리카', 'CR'),
      ('코트디부아르', 'CI'),
      ('콜롬비아', 'CO'),
      ('콩고공화국', 'CG'),
      ('콩고민주공화국', 'CD'),
      ('쿠바', 'CU'),
      ('쿠웨이트', 'KW'),
      ('크로아티아', 'HR'),
      ('키르기스스탄', 'KG'),
      ('키리바시', 'KI'),
      ('키프로스', 'CY'),
      ('타지키스탄', 'TJ'),
      ('탄자니아', 'TZ'),
      ('태국', 'TH'),
      ('터키', 'TR'),
      ('토고', 'TG'),
      ('통가', 'TO'),
      ('투르크메니스탄', 'TM'),
      ('투발루', 'TV'),
      ('튀니지', 'TN'),
      ('트리니다드토바고', 'TT'),
      ('파나마', 'PA'),
      ('파라과이', 'PY'),
      ('파키스탄', 'PK'),
      ('파푸아뉴기니', 'PG'),
      ('팔라우', 'PW'),
      ('팔레스타인', 'PS'),
      ('페루', 'PE'),
      ('포르투갈', 'PT'),
      ('폴란드', 'PL'),
      ('프랑스', 'FR'),
      ('피지', 'FJ'),
      ('핀란드', 'FI'),
      ('필리핀', 'PH'),
      ('헝가리', 'HU'),
      ('호주', 'AU'),
      ('홍콩', 'HK')
  ) AS m(legacy, iso)
 WHERE r.country IS NOT NULL
   AND upper(trim(r.country)) = upper(m.legacy)
   AND r.country <> m.iso;

-- 아르헨티나 지부 정리: 'Buenos Aires Ⅱ' 가 없어져 로마숫자 Ⅰ 이 의미를 잃었다.
-- 지부 목록(ubf_chapters.json)과 저장된 값이 어긋나면 등록 화면에서 지부가
-- 복원되지 않는다.
UPDATE registrations
   SET branch = 'Buenos Aires'
 WHERE branch = 'Buenos AiresⅠ';
