// 전세계 국가 목록 (한국어명 / 영어명)
const List<String> kCountries = [
  '가나 (Ghana)',
  '가봉 (Gabon)',
  '가이아나 (Guyana)',
  '감비아 (Gambia)',
  '과테말라 (Guatemala)',
  '그레나다 (Grenada)',
  '그리스 (Greece)',
  '기니 (Guinea)',
  '기니비사우 (Guinea-Bissau)',
  '나미비아 (Namibia)',
  '나우루 (Nauru)',
  '나이지리아 (Nigeria)',
  '남수단 (South Sudan)',
  '남아프리카공화국 (South Africa)',
  '네덜란드 (Netherlands)',
  '네팔 (Nepal)',
  '노르웨이 (Norway)',
  '뉴질랜드 (New Zealand)',
  '니제르 (Niger)',
  '니카라과 (Nicaragua)',
  '대한민국 (South Korea)',
  '덴마크 (Denmark)',
  '도미니카 (Dominica)',
  '도미니카공화국 (Dominican Republic)',
  '독일 (Germany)',
  '동티모르 (Timor-Leste)',
  '라오스 (Laos)',
  '라이베리아 (Liberia)',
  '라트비아 (Latvia)',
  '러시아 (Russia)',
  '레바논 (Lebanon)',
  '레소토 (Lesotho)',
  '루마니아 (Romania)',
  '룩셈부르크 (Luxembourg)',
  '르완다 (Rwanda)',
  '리비아 (Libya)',
  '리투아니아 (Lithuania)',
  '리히텐슈타인 (Liechtenstein)',
  '마다가스카르 (Madagascar)',
  '마셜 제도 (Marshall Islands)',
  '말라위 (Malawi)',
  '말레이시아 (Malaysia)',
  '말리 (Mali)',
  '멕시코 (Mexico)',
  '모나코 (Monaco)',
  '모로코 (Morocco)',
  '모리셔스 (Mauritius)',
  '모리타니 (Mauritania)',
  '모잠비크 (Mozambique)',
  '몬테네그로 (Montenegro)',
  '몰도바 (Moldova)',
  '몰디브 (Maldives)',
  '몰타 (Malta)',
  '몽골 (Mongolia)',
  '미국 (United States)',
  '미크로네시아 (Micronesia)',
  '미얀마 (Myanmar)',
  '바누아투 (Vanuatu)',
  '바레인 (Bahrain)',
  '바베이도스 (Barbados)',
  '바하마 (Bahamas)',
  '방글라데시 (Bangladesh)',
  '베냉 (Benin)',
  '베네수엘라 (Venezuela)',
  '베트남 (Vietnam)',
  '벨기에 (Belgium)',
  '벨라루스 (Belarus)',
  '벨리즈 (Belize)',
  '보스니아 헤르체고비나 (Bosnia and Herzegovina)',
  '보츠와나 (Botswana)',
  '볼리비아 (Bolivia)',
  '부룬디 (Burundi)',
  '부르키나파소 (Burkina Faso)',
  '부탄 (Bhutan)',
  '북마케도니아 (North Macedonia)',
  '북한 (North Korea)',
  '불가리아 (Bulgaria)',
  '브라질 (Brazil)',
  '브루나이 (Brunei)',
  '사모아 (Samoa)',
  '사우디아라비아 (Saudi Arabia)',
  '산마리노 (San Marino)',
  '상투메 프린시페 (Sao Tome and Principe)',
  '세네갈 (Senegal)',
  '세르비아 (Serbia)',
  '세이셸 (Seychelles)',
  '세인트루시아 (Saint Lucia)',
  '세인트빈센트 그레나딘 (Saint Vincent and the Grenadines)',
  '세인트키츠 네비스 (Saint Kitts and Nevis)',
  '소말리아 (Somalia)',
  '솔로몬 제도 (Solomon Islands)',
  '수단 (Sudan)',
  '수리남 (Suriname)',
  '스리랑카 (Sri Lanka)',
  '스웨덴 (Sweden)',
  '스위스 (Switzerland)',
  '스페인 (Spain)',
  '슬로바키아 (Slovakia)',
  '슬로베니아 (Slovenia)',
  '시리아 (Syria)',
  '시에라리온 (Sierra Leone)',
  '싱가포르 (Singapore)',
  '아랍에미리트 (UAE)',
  '아르메니아 (Armenia)',
  '아르헨티나 (Argentina)',
  '아이슬란드 (Iceland)',
  '아이티 (Haiti)',
  '아일랜드 (Ireland)',
  '아제르바이잔 (Azerbaijan)',
  '아프가니스탄 (Afghanistan)',
  '안도라 (Andorra)',
  '알바니아 (Albania)',
  '알제리 (Algeria)',
  '앙골라 (Angola)',
  '앤티가 바부다 (Antigua and Barbuda)',
  '에리트레아 (Eritrea)',
  '에스와티니 (Eswatini)',
  '에스토니아 (Estonia)',
  '에콰도르 (Ecuador)',
  '에티오피아 (Ethiopia)',
  '엘살바도르 (El Salvador)',
  '영국 (United Kingdom)',
  '예멘 (Yemen)',
  '오만 (Oman)',
  '오스트리아 (Austria)',
  '온두라스 (Honduras)',
  '요르단 (Jordan)',
  '우간다 (Uganda)',
  '우루과이 (Uruguay)',
  '우즈베키스탄 (Uzbekistan)',
  '우크라이나 (Ukraine)',
  '이라크 (Iraq)',
  '이란 (Iran)',
  '이스라엘 (Israel)',
  '이집트 (Egypt)',
  '이탈리아 (Italy)',
  '인도 (India)',
  '인도네시아 (Indonesia)',
  '일본 (Japan)',
  '자메이카 (Jamaica)',
  '잠비아 (Zambia)',
  '적도 기니 (Equatorial Guinea)',
  '조지아 (Georgia)',
  '중국 (China)',
  '중앙아프리카공화국 (Central African Republic)',
  '지부티 (Djibouti)',
  '짐바브웨 (Zimbabwe)',
  '차드 (Chad)',
  '체코 (Czech Republic)',
  '칠레 (Chile)',
  '카메룬 (Cameroon)',
  '카보베르데 (Cape Verde)',
  '카자흐스탄 (Kazakhstan)',
  '카타르 (Qatar)',
  '캄보디아 (Cambodia)',
  '캐나다 (Canada)',
  '케냐 (Kenya)',
  '코모로 (Comoros)',
  '코스타리카 (Costa Rica)',
  '코트디부아르 (Côte d\'Ivoire)',
  '콜롬비아 (Colombia)',
  '콩고공화국 (Republic of the Congo)',
  '콩고민주공화국 (DR Congo)',
  '쿠바 (Cuba)',
  '쿠웨이트 (Kuwait)',
  '크로아티아 (Croatia)',
  '키르기스스탄 (Kyrgyzstan)',
  '키리바시 (Kiribati)',
  '키프로스 (Cyprus)',
  '타지키스탄 (Tajikistan)',
  '탄자니아 (Tanzania)',
  '태국 (Thailand)',
  '터키 (Turkey)',
  '토고 (Togo)',
  '통가 (Tonga)',
  '투르크메니스탄 (Turkmenistan)',
  '투발루 (Tuvalu)',
  '튀니지 (Tunisia)',
  '트리니다드 토바고 (Trinidad and Tobago)',
  '파나마 (Panama)',
  '파라과이 (Paraguay)',
  '파키스탄 (Pakistan)',
  '파푸아뉴기니 (Papua New Guinea)',
  '팔라우 (Palau)',
  '페루 (Peru)',
  '포르투갈 (Portugal)',
  '폴란드 (Poland)',
  '프랑스 (France)',
  '피지 (Fiji)',
  '핀란드 (Finland)',
  '필리핀 (Philippines)',
  '헝가리 (Hungary)',
  '호주 (Australia)',
  '홍콩 (Hong Kong)',
  '대만 (Taiwan)',
];
