// 국가 목록. **생성 파일이므로 손으로 고치지 말 것.**
// 고칠 때는 scripts/countries_table.py 를 고치고 scripts/gen_countries.py 를 돌린다.
//
// **저장하는 값은 ISO 3166-1 alpha-2 코드**이고, 화면에 보이는 이름은 영어다.
// 사용자 언어가 한국어든 스페인어든 국가명은 영어로 통일한다 — 국가명을
// 번역해 두면 같은 나라가 언어마다 다른 문자열이 되어 비교가 깨진다.
//
// 예전에는 표시명을 그대로 저장했고, 그 표시명의 출처가 두 개였다.
// users.region 에는 '아르헨티나'(한글), registrations.country 에는
// 'ARGENTINA'(영문)가 들어가 같은 나라를 가리키면서도 절대 일치하지 않았다.
// 국내 참석자 판정·코호트 집계·봉사 자격이 모두 조용히 틀렸다.
// 019 마이그레이션이 기존 값을 코드로 되돌린다.

class Country {
  /// DB 에 저장되는 값.
  final String iso;

  /// 화면 표시명. 항상 영어다.
  final String name;

  const Country(this.iso, this.name);
}

class WorldCountries {
  const WorldCountries._();

  /// 영문명 순으로 정렬돼 있다. 화면에서 그대로 쓰면 된다.
  static const List<Country> all = [
    Country('AF', 'Afghanistan'),
    Country('AL', 'Albania'),
    Country('DZ', 'Algeria'),
    Country('AD', 'Andorra'),
    Country('AO', 'Angola'),
    Country('AR', 'Argentina'),
    Country('AM', 'Armenia'),
    Country('AU', 'Australia'),
    Country('AT', 'Austria'),
    Country('AZ', 'Azerbaijan'),
    Country('BS', 'Bahamas'),
    Country('BH', 'Bahrain'),
    Country('BD', 'Bangladesh'),
    Country('BB', 'Barbados'),
    Country('BY', 'Belarus'),
    Country('BE', 'Belgium'),
    Country('BZ', 'Belize'),
    Country('BJ', 'Benin'),
    Country('BT', 'Bhutan'),
    Country('BO', 'Bolivia'),
    Country('BA', 'Bosnia and Herzegovina'),
    Country('BW', 'Botswana'),
    Country('BR', 'Brazil'),
    Country('BN', 'Brunei'),
    Country('BG', 'Bulgaria'),
    Country('BF', 'Burkina Faso'),
    Country('BI', 'Burundi'),
    Country('CV', 'Cabo Verde'),
    Country('KH', 'Cambodia'),
    Country('CM', 'Cameroon'),
    Country('CA', 'Canada'),
    Country('CF', 'Central African Republic'),
    Country('TD', 'Chad'),
    Country('CL', 'Chile'),
    Country('CN', 'China'),
    Country('CO', 'Colombia'),
    Country('CR', 'Costa Rica'),
    Country('HR', 'Croatia'),
    Country('CU', 'Cuba'),
    Country('CY', 'Cyprus'),
    Country('CZ', 'Czechia'),
    Country('CI', 'Côte d\'Ivoire'),
    Country('CD', 'DR Congo'),
    Country('DK', 'Denmark'),
    Country('DJ', 'Djibouti'),
    Country('DO', 'Dominican Republic'),
    Country('EC', 'Ecuador'),
    Country('EG', 'Egypt'),
    Country('SV', 'El Salvador'),
    Country('GQ', 'Equatorial Guinea'),
    Country('ER', 'Eritrea'),
    Country('EE', 'Estonia'),
    Country('SZ', 'Eswatini'),
    Country('ET', 'Ethiopia'),
    Country('FJ', 'Fiji'),
    Country('FI', 'Finland'),
    Country('FR', 'France'),
    Country('GA', 'Gabon'),
    Country('GM', 'Gambia'),
    Country('GE', 'Georgia'),
    Country('DE', 'Germany'),
    Country('GH', 'Ghana'),
    Country('GR', 'Greece'),
    Country('GT', 'Guatemala'),
    Country('GN', 'Guinea'),
    Country('GW', 'Guinea-Bissau'),
    Country('GY', 'Guyana'),
    Country('HT', 'Haiti'),
    Country('HN', 'Honduras'),
    Country('HK', 'Hong Kong'),
    Country('HU', 'Hungary'),
    Country('IS', 'Iceland'),
    Country('IN', 'India'),
    Country('ID', 'Indonesia'),
    Country('IR', 'Iran'),
    Country('IQ', 'Iraq'),
    Country('IE', 'Ireland'),
    Country('IL', 'Israel'),
    Country('IT', 'Italy'),
    Country('JM', 'Jamaica'),
    Country('JP', 'Japan'),
    Country('JO', 'Jordan'),
    Country('KZ', 'Kazakhstan'),
    Country('KE', 'Kenya'),
    Country('KI', 'Kiribati'),
    Country('XK', 'Kosovo'),
    Country('KW', 'Kuwait'),
    Country('KG', 'Kyrgyzstan'),
    Country('LA', 'Laos'),
    Country('LV', 'Latvia'),
    Country('LB', 'Lebanon'),
    Country('LS', 'Lesotho'),
    Country('LR', 'Liberia'),
    Country('LY', 'Libya'),
    Country('LI', 'Liechtenstein'),
    Country('LT', 'Lithuania'),
    Country('LU', 'Luxembourg'),
    Country('MO', 'Macau'),
    Country('MG', 'Madagascar'),
    Country('MW', 'Malawi'),
    Country('MY', 'Malaysia'),
    Country('MV', 'Maldives'),
    Country('ML', 'Mali'),
    Country('MT', 'Malta'),
    Country('MH', 'Marshall Islands'),
    Country('MU', 'Mauritius'),
    Country('MX', 'Mexico'),
    Country('FM', 'Micronesia'),
    Country('MD', 'Moldova'),
    Country('MC', 'Monaco'),
    Country('MN', 'Mongolia'),
    Country('ME', 'Montenegro'),
    Country('MA', 'Morocco'),
    Country('MZ', 'Mozambique'),
    Country('MM', 'Myanmar'),
    Country('NA', 'Namibia'),
    Country('NR', 'Nauru'),
    Country('NP', 'Nepal'),
    Country('NL', 'Netherlands'),
    Country('NZ', 'New Zealand'),
    Country('NI', 'Nicaragua'),
    Country('NE', 'Niger'),
    Country('NG', 'Nigeria'),
    Country('KP', 'North Korea'),
    Country('MK', 'North Macedonia'),
    Country('NO', 'Norway'),
    Country('OM', 'Oman'),
    Country('PK', 'Pakistan'),
    Country('PW', 'Palau'),
    Country('PS', 'Palestine'),
    Country('PA', 'Panama'),
    Country('PG', 'Papua New Guinea'),
    Country('PY', 'Paraguay'),
    Country('PE', 'Peru'),
    Country('PH', 'Philippines'),
    Country('PL', 'Poland'),
    Country('PT', 'Portugal'),
    Country('QA', 'Qatar'),
    Country('CG', 'Republic of the Congo'),
    Country('RO', 'Romania'),
    Country('RU', 'Russia'),
    Country('RW', 'Rwanda'),
    Country('WS', 'Samoa'),
    Country('SM', 'San Marino'),
    Country('SA', 'Saudi Arabia'),
    Country('SN', 'Senegal'),
    Country('RS', 'Serbia'),
    Country('SC', 'Seychelles'),
    Country('SL', 'Sierra Leone'),
    Country('SG', 'Singapore'),
    Country('SK', 'Slovakia'),
    Country('SI', 'Slovenia'),
    Country('SB', 'Solomon Islands'),
    Country('SO', 'Somalia'),
    Country('ZA', 'South Africa'),
    Country('KR', 'South Korea'),
    Country('SS', 'South Sudan'),
    Country('ES', 'Spain'),
    Country('LK', 'Sri Lanka'),
    Country('SD', 'Sudan'),
    Country('SR', 'Suriname'),
    Country('SE', 'Sweden'),
    Country('CH', 'Switzerland'),
    Country('SY', 'Syria'),
    Country('ST', 'São Tomé and Príncipe'),
    Country('TW', 'Taiwan'),
    Country('TJ', 'Tajikistan'),
    Country('TZ', 'Tanzania'),
    Country('TH', 'Thailand'),
    Country('TL', 'Timor-Leste'),
    Country('TG', 'Togo'),
    Country('TO', 'Tonga'),
    Country('TT', 'Trinidad and Tobago'),
    Country('TN', 'Tunisia'),
    Country('TM', 'Turkmenistan'),
    Country('TV', 'Tuvalu'),
    Country('TR', 'Türkiye'),
    Country('UG', 'Uganda'),
    Country('UA', 'Ukraine'),
    Country('AE', 'United Arab Emirates'),
    Country('GB', 'United Kingdom'),
    Country('US', 'United States'),
    Country('UY', 'Uruguay'),
    Country('UZ', 'Uzbekistan'),
    Country('VU', 'Vanuatu'),
    Country('VA', 'Vatican City'),
    Country('VE', 'Venezuela'),
    Country('VN', 'Vietnam'),
    Country('YE', 'Yemen'),
    Country('ZM', 'Zambia'),
    Country('ZW', 'Zimbabwe'),
  ];

  static const Map<String, String> _byIso = {
    'AF': 'Afghanistan',
    'AL': 'Albania',
    'DZ': 'Algeria',
    'AD': 'Andorra',
    'AO': 'Angola',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AU': 'Australia',
    'AT': 'Austria',
    'AZ': 'Azerbaijan',
    'BS': 'Bahamas',
    'BH': 'Bahrain',
    'BD': 'Bangladesh',
    'BB': 'Barbados',
    'BY': 'Belarus',
    'BE': 'Belgium',
    'BZ': 'Belize',
    'BJ': 'Benin',
    'BT': 'Bhutan',
    'BO': 'Bolivia',
    'BA': 'Bosnia and Herzegovina',
    'BW': 'Botswana',
    'BR': 'Brazil',
    'BN': 'Brunei',
    'BG': 'Bulgaria',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'CV': 'Cabo Verde',
    'KH': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CL': 'Chile',
    'CN': 'China',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'HR': 'Croatia',
    'CU': 'Cuba',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'CI': 'Côte d\'Ivoire',
    'CD': 'DR Congo',
    'DK': 'Denmark',
    'DJ': 'Djibouti',
    'DO': 'Dominican Republic',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'SV': 'El Salvador',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'EE': 'Estonia',
    'SZ': 'Eswatini',
    'ET': 'Ethiopia',
    'FJ': 'Fiji',
    'FI': 'Finland',
    'FR': 'France',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GR': 'Greece',
    'GT': 'Guatemala',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HT': 'Haiti',
    'HN': 'Honduras',
    'HK': 'Hong Kong',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran',
    'IQ': 'Iraq',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IT': 'Italy',
    'JM': 'Jamaica',
    'JP': 'Japan',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KI': 'Kiribati',
    'XK': 'Kosovo',
    'KW': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': 'Laos',
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'LI': 'Liechtenstein',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'MO': 'Macau',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'MY': 'Malaysia',
    'MV': 'Maldives',
    'ML': 'Mali',
    'MT': 'Malta',
    'MH': 'Marshall Islands',
    'MU': 'Mauritius',
    'MX': 'Mexico',
    'FM': 'Micronesia',
    'MD': 'Moldova',
    'MC': 'Monaco',
    'MN': 'Mongolia',
    'ME': 'Montenegro',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibia',
    'NR': 'Nauru',
    'NP': 'Nepal',
    'NL': 'Netherlands',
    'NZ': 'New Zealand',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'KP': 'North Korea',
    'MK': 'North Macedonia',
    'NO': 'Norway',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PW': 'Palau',
    'PS': 'Palestine',
    'PA': 'Panama',
    'PG': 'Papua New Guinea',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PL': 'Poland',
    'PT': 'Portugal',
    'QA': 'Qatar',
    'CG': 'Republic of the Congo',
    'RO': 'Romania',
    'RU': 'Russia',
    'RW': 'Rwanda',
    'WS': 'Samoa',
    'SM': 'San Marino',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SG': 'Singapore',
    'SK': 'Slovakia',
    'SI': 'Slovenia',
    'SB': 'Solomon Islands',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'KR': 'South Korea',
    'SS': 'South Sudan',
    'ES': 'Spain',
    'LK': 'Sri Lanka',
    'SD': 'Sudan',
    'SR': 'Suriname',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'SY': 'Syria',
    'ST': 'São Tomé and Príncipe',
    'TW': 'Taiwan',
    'TJ': 'Tajikistan',
    'TZ': 'Tanzania',
    'TH': 'Thailand',
    'TL': 'Timor-Leste',
    'TG': 'Togo',
    'TO': 'Tonga',
    'TT': 'Trinidad and Tobago',
    'TN': 'Tunisia',
    'TM': 'Turkmenistan',
    'TV': 'Tuvalu',
    'TR': 'Türkiye',
    'UG': 'Uganda',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom',
    'US': 'United States',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VU': 'Vanuatu',
    'VA': 'Vatican City',
    'VE': 'Venezuela',
    'VN': 'Vietnam',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe',
  };

  /// ISO 코드로 표시명을 얻는다. 모르는 코드면 코드를 그대로 돌려준다 —
  /// 빈칸을 보여주면 값이 없는 것인지 모르는 것인지 구분되지 않는다.
  static String? nameOf(String? iso) {
    if (iso == null || iso.isEmpty) return null;
    return _byIso[iso] ?? iso;
  }

  static bool isKnown(String? iso) => iso != null && _byIso.containsKey(iso);

  /// 저장된 값이 무엇이든 화면에 보일 영문 국가명으로.
  ///
  /// 019 마이그레이션이 놓친 행과 예전 버전 앱이 저장한 값이 섞여 있을 수 있어
  /// 표시 지점에서는 항상 이것을 쓴다. 해석되지 않으면 원래 값을 그대로 보여준다.
  static String? display(String? value) {
    if (value == null || value.trim().isEmpty) return null;
    final iso = isoForLegacy(value);
    return iso == null ? value : nameOf(iso);
  }

  /// 예전 표기(한글 표시명, UBF 지부 목록의 영문 표기)를 ISO 로 되돌린다.
  /// 이미 ISO 면 그대로 돌려준다.
  static String? isoForLegacy(String? value) {
    if (value == null) return null;
    final v = value.trim();
    if (v.isEmpty) return null;
    if (_byIso.containsKey(v)) return v;
    return _legacy[v] ?? _legacy[v.toUpperCase()];
  }

  // 예전 표기 → ISO. 한글 표시명, 영문명(대문자), UBF 지부 목록의 어긋난 표기.
  static const Map<String, String> _legacy = {
    'AFGHANISTAN': 'AF',
    'ALBANIA': 'AL',
    'ALGERIA': 'DZ',
    'ANDORRA': 'AD',
    'ANGOLA': 'AO',
    'ARGENTINA': 'AR',
    'ARMENIA': 'AM',
    'AUSTRALIA': 'AU',
    'AUSTRIA': 'AT',
    'AZERBAIJAN': 'AZ',
    'BAHAMAS': 'BS',
    'BAHRAIN': 'BH',
    'BANGLADESH': 'BD',
    'BARBADOS': 'BB',
    'BELARUS': 'BY',
    'BELGIUM': 'BE',
    'BELIZE': 'BZ',
    'BENIN': 'BJ',
    'BHUTAN': 'BT',
    'BOLIVIA': 'BO',
    'BOSNIA AND HERZEGOVINA': 'BA',
    'BOTSWANA': 'BW',
    'BRASIL': 'BR',
    'BRAZIL': 'BR',
    'BRUNEI': 'BN',
    'BULGARIA': 'BG',
    'BURKINA FASO': 'BF',
    'BURUNDI': 'BI',
    'CABO VERDE': 'CV',
    'CAMBODIA': 'KH',
    'CAMEROON': 'CM',
    'CAMEROUN': 'CM',
    'CANADA': 'CA',
    'CENTRAL AFRICAN REPUBLIC': 'CF',
    'CHAD': 'TD',
    'CHILE': 'CL',
    'CHINA': 'CN',
    'COLOMBIA': 'CO',
    'COSTA RICA': 'CR',
    'CROATIA': 'HR',
    'CUBA': 'CU',
    'CYPRUS': 'CY',
    'CZECH REPUBLIC': 'CZ',
    'CZECHIA': 'CZ',
    'CÔTE D\'IVOIRE': 'CI',
    'DENMARK': 'DK',
    'DJIBOUTI': 'DJ',
    'DOMINICAN REPUBLIC': 'DO',
    'DR CONGO': 'CD',
    'ECUADOR': 'EC',
    'EGYPT': 'EG',
    'EL SALVADOR': 'SV',
    'EQUATORIAL GUINEA': 'GQ',
    'ERITREA': 'ER',
    'ESTONIA': 'EE',
    'ESWATINI': 'SZ',
    'ETHIOPIA': 'ET',
    'FIJI': 'FJ',
    'FINLAND': 'FI',
    'FRANCE': 'FR',
    'GABON': 'GA',
    'GAMBIA': 'GM',
    'GEORGIA': 'GE',
    'GERMANY': 'DE',
    'GHANA': 'GH',
    'GREECE': 'GR',
    'GUATEMALA': 'GT',
    'GUINEA': 'GN',
    'GUINEA-BISSAU': 'GW',
    'GUYANA': 'GY',
    'HAITI': 'HT',
    'HONDURAS': 'HN',
    'HONG KONG': 'HK',
    'HUNGARY': 'HU',
    'ICELAND': 'IS',
    'INDIA': 'IN',
    'INDONESIA': 'ID',
    'IRAN': 'IR',
    'IRAQ': 'IQ',
    'IRELAND': 'IE',
    'ISRAEL': 'IL',
    'ITALY': 'IT',
    'JAMAICA': 'JM',
    'JAPAN': 'JP',
    'JORDAN': 'JO',
    'KAZAKHSTAN': 'KZ',
    'KENYA': 'KE',
    'KIRIBATI': 'KI',
    'KOREA': 'KR',
    'KOSOVO': 'XK',
    'KUWAIT': 'KW',
    'KYRGYZSTAN': 'KG',
    'LAOS': 'LA',
    'LATVIA': 'LV',
    'LEBANON': 'LB',
    'LESOTHO': 'LS',
    'LIBERIA': 'LR',
    'LIBYA': 'LY',
    'LIECHTENSTEIN': 'LI',
    'LITHUANIA': 'LT',
    'LUXEMBOURG': 'LU',
    'MACAU': 'MO',
    'MADAGASCAR': 'MG',
    'MALAWI': 'MW',
    'MALAYSIA': 'MY',
    'MALDIVES': 'MV',
    'MALI': 'ML',
    'MALTA': 'MT',
    'MARSHALL ISLANDS': 'MH',
    'MAURITIUS': 'MU',
    'MEXICO': 'MX',
    'MICRONESIA': 'FM',
    'MOLDOVA': 'MD',
    'MONACO': 'MC',
    'MONGOLIA': 'MN',
    'MONTENEGRO': 'ME',
    'MOROCCO': 'MA',
    'MOZAMBIQUE': 'MZ',
    'MYANMAR': 'MM',
    'NAMIBIA': 'NA',
    'NAURU': 'NR',
    'NEPAL': 'NP',
    'NETHERLANDS': 'NL',
    'NEW ZEALAND': 'NZ',
    'NICARAGUA': 'NI',
    'NIGER': 'NE',
    'NIGERIA': 'NG',
    'NORTH KOREA': 'KP',
    'NORTH MACEDONIA': 'MK',
    'NORWAY': 'NO',
    'OMAN': 'OM',
    'PAKISTAN': 'PK',
    'PALAU': 'PW',
    'PALESTINE': 'PS',
    'PANAMA': 'PA',
    'PAPUA NEW GUINEA': 'PG',
    'PARAGUAY': 'PY',
    'PERU': 'PE',
    'PHILIPPINES': 'PH',
    'POLAND': 'PL',
    'PORTUGAL': 'PT',
    'QATAR': 'QA',
    'REPUBLIC OF THE CONGO': 'CG',
    'ROMANIA': 'RO',
    'RUSSIA': 'RU',
    'RWANDA': 'RW',
    'SAMOA': 'WS',
    'SAN MARINO': 'SM',
    'SAUDI ARABIA': 'SA',
    'SENEGAL': 'SN',
    'SERBIA': 'RS',
    'SEYCHELLES': 'SC',
    'SIERRA LEONE': 'SL',
    'SINGAPORE': 'SG',
    'SLOVAKIA': 'SK',
    'SLOVENIA': 'SI',
    'SOLOMON ISLANDS': 'SB',
    'SOMALIA': 'SO',
    'SOUTH AFRICA': 'ZA',
    'SOUTH KOREA': 'KR',
    'SOUTH SUDAN': 'SS',
    'SPAIN': 'ES',
    'SRI LANKA': 'LK',
    'SRI-LANKA': 'LK',
    'SUDAN': 'SD',
    'SURINAME': 'SR',
    'SWEDEN': 'SE',
    'SWITZERLAND': 'CH',
    'SYRIA': 'SY',
    'SÃO TOMÉ AND PRÍNCIPE': 'ST',
    'TAIWAN': 'TW',
    'TAJIKISTAN': 'TJ',
    'TANZANIA': 'TZ',
    'THAILAND': 'TH',
    'TIMOR-LESTE': 'TL',
    'TOGO': 'TG',
    'TONGA': 'TO',
    'TRINIDAD AND TOBAGO': 'TT',
    'TUNISIA': 'TN',
    'TURKEY': 'TR',
    'TURKMENISTAN': 'TM',
    'TUVALU': 'TV',
    'TÜRKIYE': 'TR',
    'U. S. A.': 'US',
    'UGANDA': 'UG',
    'UKRAINE': 'UA',
    'UNITED ARAB EMIRATES': 'AE',
    'UNITED KINGDOM': 'GB',
    'UNITED STATES': 'US',
    'URUGUAY': 'UY',
    'UZBEKISTAN': 'UZ',
    'VANUATU': 'VU',
    'VATICAN CITY': 'VA',
    'VENEZUELA': 'VE',
    'VIETNAM': 'VN',
    'YEMEN': 'YE',
    'ZAMBIA': 'ZM',
    'ZIMBABWE': 'ZW',
    '가나': 'GH',
    '가봉': 'GA',
    '가이아나': 'GY',
    '감비아': 'GM',
    '과테말라': 'GT',
    '그리스': 'GR',
    '기니': 'GN',
    '기니비사우': 'GW',
    '나미비아': 'NA',
    '나우루': 'NR',
    '나이지리아': 'NG',
    '남수단': 'SS',
    '남아프리카공화국': 'ZA',
    '네덜란드': 'NL',
    '네팔': 'NP',
    '노르웨이': 'NO',
    '뉴질랜드': 'NZ',
    '니제르': 'NE',
    '니카라과': 'NI',
    '대만': 'TW',
    '대한민국': 'KR',
    '덴마크': 'DK',
    '도미니카공화국': 'DO',
    '독일': 'DE',
    '동티모르': 'TL',
    '라오스': 'LA',
    '라이베리아': 'LR',
    '라트비아': 'LV',
    '러시아': 'RU',
    '레바논': 'LB',
    '레소토': 'LS',
    '루마니아': 'RO',
    '룩셈부르크': 'LU',
    '르완다': 'RW',
    '리비아': 'LY',
    '리투아니아': 'LT',
    '리히텐슈타인': 'LI',
    '마다가스카르': 'MG',
    '마셜제도': 'MH',
    '마카오': 'MO',
    '말라위': 'MW',
    '말레이시아': 'MY',
    '말리': 'ML',
    '멕시코': 'MX',
    '모나코': 'MC',
    '모로코': 'MA',
    '모리셔스': 'MU',
    '모잠비크': 'MZ',
    '몬테네그로': 'ME',
    '몰도바': 'MD',
    '몰디브': 'MV',
    '몰타': 'MT',
    '몽골': 'MN',
    '미국': 'US',
    '미얀마': 'MM',
    '미크로네시아': 'FM',
    '바누아투': 'VU',
    '바레인': 'BH',
    '바베이도스': 'BB',
    '바티칸': 'VA',
    '바하마': 'BS',
    '방글라데시': 'BD',
    '베냉': 'BJ',
    '베네수엘라': 'VE',
    '베트남': 'VN',
    '벨기에': 'BE',
    '벨라루스': 'BY',
    '벨리즈': 'BZ',
    '보스니아헤르체고비나': 'BA',
    '보츠와나': 'BW',
    '볼리비아': 'BO',
    '부룬디': 'BI',
    '부르키나파소': 'BF',
    '부탄': 'BT',
    '북마케도니아': 'MK',
    '북한': 'KP',
    '불가리아': 'BG',
    '브라질': 'BR',
    '브루나이': 'BN',
    '사모아': 'WS',
    '사우디아라비아': 'SA',
    '산마리노': 'SM',
    '상투메프린시페': 'ST',
    '세네갈': 'SN',
    '세르비아': 'RS',
    '세이셸': 'SC',
    '소말리아': 'SO',
    '솔로몬제도': 'SB',
    '수단': 'SD',
    '수리남': 'SR',
    '스리랑카': 'LK',
    '스웨덴': 'SE',
    '스위스': 'CH',
    '스페인': 'ES',
    '슬로바키아': 'SK',
    '슬로베니아': 'SI',
    '시리아': 'SY',
    '시에라리온': 'SL',
    '싱가포르': 'SG',
    '아랍에미리트': 'AE',
    '아르메니아': 'AM',
    '아르헨티나': 'AR',
    '아이슬란드': 'IS',
    '아이티': 'HT',
    '아일랜드': 'IE',
    '아제르바이잔': 'AZ',
    '아프가니스탄': 'AF',
    '안도라': 'AD',
    '알바니아': 'AL',
    '알제리': 'DZ',
    '앙골라': 'AO',
    '에리트레아': 'ER',
    '에스와티니': 'SZ',
    '에스토니아': 'EE',
    '에콰도르': 'EC',
    '에티오피아': 'ET',
    '엘살바도르': 'SV',
    '영국': 'GB',
    '예멘': 'YE',
    '오만': 'OM',
    '오스트리아': 'AT',
    '온두라스': 'HN',
    '요르단': 'JO',
    '우간다': 'UG',
    '우루과이': 'UY',
    '우즈베키스탄': 'UZ',
    '우크라이나': 'UA',
    '이라크': 'IQ',
    '이란': 'IR',
    '이스라엘': 'IL',
    '이집트': 'EG',
    '이탈리아': 'IT',
    '인도': 'IN',
    '인도네시아': 'ID',
    '일본': 'JP',
    '자메이카': 'JM',
    '잠비아': 'ZM',
    '적도기니': 'GQ',
    '조지아': 'GE',
    '중국': 'CN',
    '중앙아프리카공화국': 'CF',
    '지부티': 'DJ',
    '짐바브웨': 'ZW',
    '차드': 'TD',
    '체코': 'CZ',
    '칠레': 'CL',
    '카메룬': 'CM',
    '카보베르데': 'CV',
    '카자흐스탄': 'KZ',
    '카타르': 'QA',
    '캄보디아': 'KH',
    '캐나다': 'CA',
    '케냐': 'KE',
    '코소보': 'XK',
    '코스타리카': 'CR',
    '코트디부아르': 'CI',
    '콜롬비아': 'CO',
    '콩고공화국': 'CG',
    '콩고민주공화국': 'CD',
    '쿠바': 'CU',
    '쿠웨이트': 'KW',
    '크로아티아': 'HR',
    '키르기스스탄': 'KG',
    '키리바시': 'KI',
    '키프로스': 'CY',
    '타지키스탄': 'TJ',
    '탄자니아': 'TZ',
    '태국': 'TH',
    '터키': 'TR',
    '토고': 'TG',
    '통가': 'TO',
    '투르크메니스탄': 'TM',
    '투발루': 'TV',
    '튀니지': 'TN',
    '트리니다드토바고': 'TT',
    '파나마': 'PA',
    '파라과이': 'PY',
    '파키스탄': 'PK',
    '파푸아뉴기니': 'PG',
    '팔라우': 'PW',
    '팔레스타인': 'PS',
    '페루': 'PE',
    '포르투갈': 'PT',
    '폴란드': 'PL',
    '프랑스': 'FR',
    '피지': 'FJ',
    '핀란드': 'FI',
    '필리핀': 'PH',
    '헝가리': 'HU',
    '호주': 'AU',
    '홍콩': 'HK',
  };
}
