# 국가 레지스트리 원본. 여기서 Dart 파일을 생성한다.
# (ko, iso, en, es) — ko 는 기존 world_countries.dart 의 표기를 그대로 유지한다.
# 기존 저장값이 한글 표기이므로, 표기가 달라지면 마이그레이션이 그 행을 놓친다.

TABLE = [
    ('대한민국', 'KR', 'South Korea', 'Corea del Sur'),
    ('북한', 'KP', 'North Korea', 'Corea del Norte'),
    ('일본', 'JP', 'Japan', 'Japón'),
    ('중국', 'CN', 'China', 'China'),
    ('대만', 'TW', 'Taiwan', 'Taiwán'),
    ('홍콩', 'HK', 'Hong Kong', 'Hong Kong'),
    ('마카오', 'MO', 'Macau', 'Macao'),
    ('몽골', 'MN', 'Mongolia', 'Mongolia'),
    ('미국', 'US', 'United States', 'Estados Unidos'),
    ('캐나다', 'CA', 'Canada', 'Canadá'),
    ('멕시코', 'MX', 'Mexico', 'México'),
    ('과테말라', 'GT', 'Guatemala', 'Guatemala'),
    ('온두라스', 'HN', 'Honduras', 'Honduras'),
    ('엘살바도르', 'SV', 'El Salvador', 'El Salvador'),
    ('니카라과', 'NI', 'Nicaragua', 'Nicaragua'),
    ('코스타리카', 'CR', 'Costa Rica', 'Costa Rica'),
    ('파나마', 'PA', 'Panama', 'Panamá'),
    ('벨리즈', 'BZ', 'Belize', 'Belice'),
    ('쿠바', 'CU', 'Cuba', 'Cuba'),
    ('자메이카', 'JM', 'Jamaica', 'Jamaica'),
    ('아이티', 'HT', 'Haiti', 'Haití'),
    ('도미니카공화국', 'DO', 'Dominican Republic', 'República Dominicana'),
    ('바하마', 'BS', 'Bahamas', 'Bahamas'),
    ('트리니다드토바고', 'TT', 'Trinidad and Tobago', 'Trinidad y Tobago'),
    ('바베이도스', 'BB', 'Barbados', 'Barbados'),
    ('아르헨티나', 'AR', 'Argentina', 'Argentina'),
    ('브라질', 'BR', 'Brazil', 'Brasil'),
    ('칠레', 'CL', 'Chile', 'Chile'),
    ('콜롬비아', 'CO', 'Colombia', 'Colombia'),
    ('페루', 'PE', 'Peru', 'Perú'),
    ('베네수엘라', 'VE', 'Venezuela', 'Venezuela'),
    ('에콰도르', 'EC', 'Ecuador', 'Ecuador'),
    ('볼리비아', 'BO', 'Bolivia', 'Bolivia'),
    ('파라과이', 'PY', 'Paraguay', 'Paraguay'),
    ('우루과이', 'UY', 'Uruguay', 'Uruguay'),
    ('가이아나', 'GY', 'Guyana', 'Guyana'),
    ('수리남', 'SR', 'Suriname', 'Surinam'),
    ('영국', 'GB', 'United Kingdom', 'Reino Unido'),
    ('아일랜드', 'IE', 'Ireland', 'Irlanda'),
    ('프랑스', 'FR', 'France', 'Francia'),
    ('독일', 'DE', 'Germany', 'Alemania'),
    ('이탈리아', 'IT', 'Italy', 'Italia'),
    ('스페인', 'ES', 'Spain', 'España'),
    ('포르투갈', 'PT', 'Portugal', 'Portugal'),
    ('네덜란드', 'NL', 'Netherlands', 'Países Bajos'),
    ('벨기에', 'BE', 'Belgium', 'Bélgica'),
    ('룩셈부르크', 'LU', 'Luxembourg', 'Luxemburgo'),
    ('스위스', 'CH', 'Switzerland', 'Suiza'),
    ('오스트리아', 'AT', 'Austria', 'Austria'),
    ('리히텐슈타인', 'LI', 'Liechtenstein', 'Liechtenstein'),
    ('모나코', 'MC', 'Monaco', 'Mónaco'),
    ('덴마크', 'DK', 'Denmark', 'Dinamarca'),
    ('스웨덴', 'SE', 'Sweden', 'Suecia'),
    ('노르웨이', 'NO', 'Norway', 'Noruega'),
    ('핀란드', 'FI', 'Finland', 'Finlandia'),
    ('아이슬란드', 'IS', 'Iceland', 'Islandia'),
    ('폴란드', 'PL', 'Poland', 'Polonia'),
    ('체코', 'CZ', 'Czechia', 'Chequia'),
    ('슬로바키아', 'SK', 'Slovakia', 'Eslovaquia'),
    ('헝가리', 'HU', 'Hungary', 'Hungría'),
    ('루마니아', 'RO', 'Romania', 'Rumania'),
    ('불가리아', 'BG', 'Bulgaria', 'Bulgaria'),
    ('그리스', 'GR', 'Greece', 'Grecia'),
    ('크로아티아', 'HR', 'Croatia', 'Croacia'),
    ('슬로베니아', 'SI', 'Slovenia', 'Eslovenia'),
    ('세르비아', 'RS', 'Serbia', 'Serbia'),
    ('보스니아헤르체고비나', 'BA', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina'),
    ('몬테네그로', 'ME', 'Montenegro', 'Montenegro'),
    ('북마케도니아', 'MK', 'North Macedonia', 'Macedonia del Norte'),
    ('알바니아', 'AL', 'Albania', 'Albania'),
    # XK 는 정식 ISO 3166-1 코드가 아니라 관례적으로 쓰이는 사용자 지정 코드다.
    ('코소보', 'XK', 'Kosovo', 'Kosovo'),
    ('우크라이나', 'UA', 'Ukraine', 'Ucrania'),
    ('벨라루스', 'BY', 'Belarus', 'Bielorrusia'),
    ('러시아', 'RU', 'Russia', 'Rusia'),
    ('몰도바', 'MD', 'Moldova', 'Moldavia'),
    ('에스토니아', 'EE', 'Estonia', 'Estonia'),
    ('라트비아', 'LV', 'Latvia', 'Letonia'),
    ('리투아니아', 'LT', 'Lithuania', 'Lituania'),
    ('몰타', 'MT', 'Malta', 'Malta'),
    ('키프로스', 'CY', 'Cyprus', 'Chipre'),
    ('안도라', 'AD', 'Andorra', 'Andorra'),
    ('산마리노', 'SM', 'San Marino', 'San Marino'),
    ('바티칸', 'VA', 'Vatican City', 'Ciudad del Vaticano'),
    ('터키', 'TR', 'Türkiye', 'Turquía'),
    ('조지아', 'GE', 'Georgia', 'Georgia'),
    ('아르메니아', 'AM', 'Armenia', 'Armenia'),
    ('아제르바이잔', 'AZ', 'Azerbaijan', 'Azerbaiyán'),
    ('이스라엘', 'IL', 'Israel', 'Israel'),
    ('팔레스타인', 'PS', 'Palestine', 'Palestina'),
    ('레바논', 'LB', 'Lebanon', 'Líbano'),
    ('요르단', 'JO', 'Jordan', 'Jordania'),
    ('시리아', 'SY', 'Syria', 'Siria'),
    ('이라크', 'IQ', 'Iraq', 'Irak'),
    ('이란', 'IR', 'Iran', 'Irán'),
    ('사우디아라비아', 'SA', 'Saudi Arabia', 'Arabia Saudita'),
    ('아랍에미리트', 'AE', 'United Arab Emirates', 'Emiratos Árabes Unidos'),
    ('카타르', 'QA', 'Qatar', 'Catar'),
    ('쿠웨이트', 'KW', 'Kuwait', 'Kuwait'),
    ('바레인', 'BH', 'Bahrain', 'Baréin'),
    ('오만', 'OM', 'Oman', 'Omán'),
    ('예멘', 'YE', 'Yemen', 'Yemen'),
    ('인도', 'IN', 'India', 'India'),
    ('파키스탄', 'PK', 'Pakistan', 'Pakistán'),
    ('방글라데시', 'BD', 'Bangladesh', 'Bangladés'),
    ('스리랑카', 'LK', 'Sri Lanka', 'Sri Lanka'),
    ('네팔', 'NP', 'Nepal', 'Nepal'),
    ('부탄', 'BT', 'Bhutan', 'Bután'),
    ('몰디브', 'MV', 'Maldives', 'Maldivas'),
    ('아프가니스탄', 'AF', 'Afghanistan', 'Afganistán'),
    ('태국', 'TH', 'Thailand', 'Tailandia'),
    ('베트남', 'VN', 'Vietnam', 'Vietnam'),
    ('필리핀', 'PH', 'Philippines', 'Filipinas'),
    ('인도네시아', 'ID', 'Indonesia', 'Indonesia'),
    ('말레이시아', 'MY', 'Malaysia', 'Malasia'),
    ('싱가포르', 'SG', 'Singapore', 'Singapur'),
    ('미얀마', 'MM', 'Myanmar', 'Birmania'),
    ('캄보디아', 'KH', 'Cambodia', 'Camboya'),
    ('라오스', 'LA', 'Laos', 'Laos'),
    ('브루나이', 'BN', 'Brunei', 'Brunéi'),
    ('동티모르', 'TL', 'Timor-Leste', 'Timor Oriental'),
    ('카자흐스탄', 'KZ', 'Kazakhstan', 'Kazajistán'),
    ('우즈베키스탄', 'UZ', 'Uzbekistan', 'Uzbekistán'),
    ('투르크메니스탄', 'TM', 'Turkmenistan', 'Turkmenistán'),
    ('키르기스스탄', 'KG', 'Kyrgyzstan', 'Kirguistán'),
    ('타지키스탄', 'TJ', 'Tajikistan', 'Tayikistán'),
    ('이집트', 'EG', 'Egypt', 'Egipto'),
    ('리비아', 'LY', 'Libya', 'Libia'),
    ('튀니지', 'TN', 'Tunisia', 'Túnez'),
    ('알제리', 'DZ', 'Algeria', 'Argelia'),
    ('모로코', 'MA', 'Morocco', 'Marruecos'),
    ('수단', 'SD', 'Sudan', 'Sudán'),
    ('남수단', 'SS', 'South Sudan', 'Sudán del Sur'),
    ('나이지리아', 'NG', 'Nigeria', 'Nigeria'),
    ('가나', 'GH', 'Ghana', 'Ghana'),
    ('코트디부아르', 'CI', "Côte d'Ivoire", 'Costa de Marfil'),
    ('세네갈', 'SN', 'Senegal', 'Senegal'),
    ('말리', 'ML', 'Mali', 'Malí'),
    ('부르키나파소', 'BF', 'Burkina Faso', 'Burkina Faso'),
    ('니제르', 'NE', 'Niger', 'Níger'),
    ('기니', 'GN', 'Guinea', 'Guinea'),
    ('베냉', 'BJ', 'Benin', 'Benín'),
    ('토고', 'TG', 'Togo', 'Togo'),
    ('시에라리온', 'SL', 'Sierra Leone', 'Sierra Leona'),
    ('라이베리아', 'LR', 'Liberia', 'Liberia'),
    ('감비아', 'GM', 'Gambia', 'Gambia'),
    ('기니비사우', 'GW', 'Guinea-Bissau', 'Guinea-Bisáu'),
    ('카메룬', 'CM', 'Cameroon', 'Camerún'),
    ('차드', 'TD', 'Chad', 'Chad'),
    ('중앙아프리카공화국', 'CF', 'Central African Republic', 'República Centroafricana'),
    ('가봉', 'GA', 'Gabon', 'Gabón'),
    ('콩고공화국', 'CG', 'Republic of the Congo', 'República del Congo'),
    ('콩고민주공화국', 'CD', 'DR Congo', 'República Democrática del Congo'),
    ('에티오피아', 'ET', 'Ethiopia', 'Etiopía'),
    ('케냐', 'KE', 'Kenya', 'Kenia'),
    ('탄자니아', 'TZ', 'Tanzania', 'Tanzania'),
    ('우간다', 'UG', 'Uganda', 'Uganda'),
    ('르완다', 'RW', 'Rwanda', 'Ruanda'),
    ('부룬디', 'BI', 'Burundi', 'Burundi'),
    ('소말리아', 'SO', 'Somalia', 'Somalia'),
    ('지부티', 'DJ', 'Djibouti', 'Yibuti'),
    ('에리트레아', 'ER', 'Eritrea', 'Eritrea'),
    ('남아프리카공화국', 'ZA', 'South Africa', 'Sudáfrica'),
    ('짐바브웨', 'ZW', 'Zimbabwe', 'Zimbabue'),
    ('잠비아', 'ZM', 'Zambia', 'Zambia'),
    ('모잠비크', 'MZ', 'Mozambique', 'Mozambique'),
    ('앙골라', 'AO', 'Angola', 'Angola'),
    ('나미비아', 'NA', 'Namibia', 'Namibia'),
    ('보츠와나', 'BW', 'Botswana', 'Botsuana'),
    ('말라위', 'MW', 'Malawi', 'Malaui'),
    ('레소토', 'LS', 'Lesotho', 'Lesoto'),
    ('에스와티니', 'SZ', 'Eswatini', 'Esuatini'),
    ('마다가스카르', 'MG', 'Madagascar', 'Madagascar'),
    ('모리셔스', 'MU', 'Mauritius', 'Mauricio'),
    ('세이셸', 'SC', 'Seychelles', 'Seychelles'),
    ('카보베르데', 'CV', 'Cabo Verde', 'Cabo Verde'),
    ('적도기니', 'GQ', 'Equatorial Guinea', 'Guinea Ecuatorial'),
    ('상투메프린시페', 'ST', 'São Tomé and Príncipe', 'Santo Tomé y Príncipe'),
    ('호주', 'AU', 'Australia', 'Australia'),
    ('뉴질랜드', 'NZ', 'New Zealand', 'Nueva Zelanda'),
    ('파푸아뉴기니', 'PG', 'Papua New Guinea', 'Papúa Nueva Guinea'),
    ('피지', 'FJ', 'Fiji', 'Fiyi'),
    ('솔로몬제도', 'SB', 'Solomon Islands', 'Islas Salomón'),
    ('바누아투', 'VU', 'Vanuatu', 'Vanuatu'),
    ('사모아', 'WS', 'Samoa', 'Samoa'),
    ('통가', 'TO', 'Tonga', 'Tonga'),
    ('키리바시', 'KI', 'Kiribati', 'Kiribati'),
    ('팔라우', 'PW', 'Palau', 'Palaos'),
    ('마셜제도', 'MH', 'Marshall Islands', 'Islas Marshall'),
    ('미크로네시아', 'FM', 'Micronesia', 'Micronesia'),
    ('나우루', 'NR', 'Nauru', 'Nauru'),
    ('투발루', 'TV', 'Tuvalu', 'Tuvalu'),
]

# ubf_chapters.json 의 국가명 → ISO.
# 대부분 영문명과 자명하게 대응하지만, 아래는 표기가 흔들려 자동 대응이 안 된다.
UBF_ALIASES = {
    'CAMEROUN': 'CM',          # 프랑스어 표기
    'BRASIL': 'BR',            # 포르투갈어 표기
    'U. S. A.': 'US',          # 마침표·공백 포함
    'Sri-Lanka': 'LK',         # 하이픈
    'CZECH REPUBLIC': 'CZ',    # 현재 통용명은 Czechia
    'TURKEY': 'TR',            # 현재 통용명은 Türkiye
    'KOREA': 'KR',
}
